### PR TITLE
Set base url and paths from ENV

### PR DESCRIPTION
**Pull request by avinassh**
Earlier URLs were hardcoded and badly named. There weren't different paths being used either. This PR fixes those issues.

I have added following variables which will be read from ENV: `BaseURL`, `ACCUAMAN_PATH`, `AuthRedirectPath`, `SignupPath`, `PasswordResetPath` (I have added comments in code to indicate what they are)

### CODE REVIEW

**Comment by avinassh** [comment]
closes: https://app.asana.com/0/319381497948334/320269400300757

**Comment by ofpiyush** [comment]
bada sundar hai, jo bhi hai. Tumne chala liya to chal raha hoga bro. <3

**Comment by ofpiyush** [comment]
@avinassh 😮 this existed

**Comment by avinassh** [comment]
Yes 😬 I guess its not required now anymore?

**Comment by ofpiyush** [comment]
whenever you find time, dekh ke merge kar do.

**Comment by avinassh** [comment]
continued in #41

**Pull request closed without merging**
