### PR TITLE
Deployment

### PR DESCRIPTION
**Pull request by ofpiyush**
Plis to test if mail is sent etc

### CODE REVIEW

**Comment by avinassh** [comment]
Closes #15

**Comment by avinassh** [comment]
Closes #17

**Comment by ofpiyush** [comment]
can we merge and close this?

**Comment by avinassh** [comment]
Give me couple of minutes

**Comment by avinassh** [comment]
Tested locally. Works. 

on GC, it is failing to connect to Entity server. Merging this PR now.

**Pull request merged**
